backend:
  name: git-gateway
  branch: master

media_folder: static/images
public_folder: /images

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "src/imageGalleries"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "image-gallery",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - label: "Gallery"
        name: "galleryImages"
        widget: "list"
        field: { label: Image, name: image, widget: image }
  - name: "generic"
    label: "Generic"
    folder: "src/content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "generic-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Main Content", name: "minContent", widget: "text" }
